### EXPERIMENT SPECIFIC 
basecalled_dir: "/ssd_workspace/jpeter/ssData/Guppy_basecalling/FLEPseq/RUN22_Spike_in/workspace/" # Path to fast5 files
outdir: "/home/jpeter/DATA/FLEPseq/Spike_in_v2.1/"
barcode_corr: "/home/jpeter/DATA/FLEPseq/Spike_in_v2.1/barcode_correspondance.tsv"
sequencing_summary: "/ssd_workspace/jpeter/ssData/Guppy_basecalling/FLEPseq/RUN22_Spike_in/sequencing_summary.txt"

### OUTPUT FILES ORGANIZATION
runs_dir: "1_Runs"
mapping_dir: "2_Mapping"
polyA_dir: "3_PolyA"
tail_dir: "4_Tail"

### ANNOTATIONS
#introns_exons: "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/exon_intron_pos.repr.bed"
introns_exons: "/home/jpeter/DATA/FLEPseq/Spike_in/exon_intron.bed"
select_introns: "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/select_introns.txt"
reference_genome: "/home/jpeter/DATA/FLEPseq/Spike_in_v2.1/Spike_in_v2.1_seqs.fa" # Reference genome in fasta

#introns_exons: "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/exon_intron_pos.repr.bed"
#select_introns: "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/select_introns.txt"
#reference_genome: "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/TAIR10_chr_all.fas" # Reference genome in fasta

### MINIMAP MAPPING ADDITIONAL PARAMETERS
minimap2_add_opts: "--secondary=no -G 5000"
