### EXPERIMENT SPECIFIC 
basecalled_dir: "/ssd_workspace/jpeter/Guppy_basecalling/RUN26_ddx6/workspace/" # Path to fast5 files
outdir: "/shared/home/jpeter/Data/FLEPseq2/RUN26_ddx6/"
barcode_corr: "/shared/home/jpeter/Data/FLEPseq2/RUN26_ddx6/barcode_correspondance.tsv"
sequencing_summary: "/ssd_workspace/jpeter/Guppy_basecalling/RUN26_ddx6/sequencing_summary.txt"

### OUTPUT FILES ORGANIZATION
runs_dir: "1_Runs"
mapping_dir: "2_Mapping"
polyA_dir: "3_PolyA"
tail_dir: "4_Tail"

### ANNOTATIONS
introns_exons: "/shared/home/jpeter/Data/ReferenceGenomes/AThaliana/TAIR10/exon_intron_pos.repr.bed"
select_introns: "/shared/home/jpeter/Data/ReferenceGenomes/AThaliana/TAIR10/select_introns.txt"
reference_genome: "/shared/home/jpeter/Data/ReferenceGenomes/AThaliana/TAIR10/TAIR10_chr_all.fas" # Reference genome in fasta

### MINIMAP MAPPING ADDITIONAL PARAMETERS
minimap2_add_opts: "--secondary=no -G 5000"
