### EXPERIMENT SPECIFIC 
basecalled_dir: "/ssd_workspace/jpeter/ssData/Guppy_basecalling/FLEPseq/RUN10_rep17_GS/Col0_urt1_heso1_uh/workspace/" # Path to fast5 files
outdir: "/home/jpeter/DATA/FLEPseq/Clean_Runs/RUN10_rep17_GS_v4/"
barcode_corr: "/home/jpeter/DATA/FLEPseq/Clean_Runs/RUN10_rep17_GS_v4/barcode_correspondance.tsv"
sequencing_summary: "/home/jpeter/DATA/FLEPseq/Clean_Runs/RUN10_rep17_GS_v4/1_Runs/sequencing_summary.txt"

### OUTPUT FILES ORGANIZATION
runs_dir: "1_Runs"
mapping_dir: "2_Mapping"
polyA_dir: "3_PolyA"
tail_dir: "4_Tail"

### ANNOTATIONS
introns_exons: "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/exon_intron_pos.repr.bed"
select_introns: "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/select_introns.txt"
reference_genome: "/home/jpeter/DATA/ReferenceGenomes/Athaliana/TAIR10/TAIR10_chr_all.fas" # Reference genome in fasta

### MINIMAP MAPPING ADDITIONAL PARAMETERS
minimap2_add_opts: "--secondary=no -G 5000"
